import { jsx as _jsx, jsxs as _jsxs } from "nativewind/jsx-runtime";
import { View, ScrollView } from 'react-native';
import { Text, H1, H2, Lead, Small } from '../../ui/typography';
import { Card, CardContent } from '../../ui/card';
import { Layout, Zap, BarChart3 } from 'lucide-react-native';
import { Button } from '../../ui/button';
export function LandingScreen() {
    return (_jsxs(ScrollView, { className: "flex-1 bg-white", children: [_jsxs(View, { className: "flex-row items-center justify-between px-6 py-4 border-b border-slate-100", children: [_jsx(H2, { className: "text-blue-600 font-bold tracking-tight", children: "GrowthPad" }), _jsxs(View, { className: "flex-row gap-4", children: [_jsx(Button, { label: "Sign In", variant: "ghost", href: "/login" }), _jsx(Button, { label: "Get Started", variant: "primary", size: "sm", href: "/login" })] })] }), _jsxs(View, { className: "px-6 py-16 items-center text-center", children: [_jsx(View, { className: "bg-blue-50 px-3 py-1 rounded-full mb-6", children: _jsx(Small, { className: "text-blue-700 font-bold", children: "2025 READY ARCHITECTURE" }) }), _jsxs(H1, { className: "text-slate-900 text-center mb-6", children: ["Accelerate Your Business ", _jsx(Text, { className: "text-blue-600", children: "Growth" })] }), _jsx(Lead, { className: "text-slate-500 text-center max-w-2xl", children: "The unified strategic playbook canvas for modern SaaS founders. Manage objectives, track jobs, and scale with conviction." }), _jsxs(View, { className: "mt-10 flex-row gap-4", children: [_jsx(Button, { label: "Build Your Workboard", size: "lg", href: "/login" }), _jsx(Button, { label: "View Demo", variant: "outline", size: "lg" })] })] }), _jsxs(View, { className: "px-6 py-16 bg-slate-50", children: [_jsxs(View, { className: "items-center mb-12", children: [_jsx(H2, { className: "text-slate-900 mb-2", children: "Everything you need to scale" }), _jsx(Text, { className: "text-slate-500", children: "Built for speed, efficiency, and clarity." })] }), _jsxs(View, { className: "gap-6 md:flex-row flex-wrap justify-center", children: [_jsx(FeatureCard, { icon: Layout, title: "Workboard", desc: "Visualize your entire strategic cascade from Pillars to Jobs." }), _jsx(FeatureCard, { icon: Zap, title: "AI Simulation", desc: "Generate resources and simulate growth scenarios instantly." }), _jsx(FeatureCard, { icon: BarChart3, title: "Analytics", desc: "Real-time tracking of operational and financial health." })] })] }), _jsx(View, { className: "p-12 items-center border-t border-slate-100", children: _jsx(Text, { className: "text-slate-400", children: "\u00A9 2025 GrowthPad. All rights reserved." }) })] }));
}
function FeatureCard({ icon: Icon, title, desc }) {
    return (_jsx(Card, { className: "w-full md:w-[300px] bg-white border-none shadow-sm", children: _jsxs(CardContent, { className: "p-6", children: [_jsx(View, { className: "w-12 h-12 bg-blue-50 rounded-lg items-center justify-center mb-4", children: _jsx(Icon, { color: "#2563eb", size: 24 }) }), _jsx(H2, { className: "text-lg mb-2", children: title }), _jsx(Text, { className: "text-slate-500 leading-relaxed", children: desc })] }) }));
}
