import { jsx as _jsx, jsxs as _jsxs } from "nativewind/jsx-runtime";
import { View, ScrollView } from 'react-native';
import { H1, Lead, Text, Small } from '../../ui/typography';
import { Button } from '../../ui/button';
import { Card, CardContent, CardHeader } from '../../ui/card';
import { Shield, ChevronLeft, Chrome } from 'lucide-react-native';
export function LoginScreen() {
    return (_jsx(ScrollView, { className: "flex-1 bg-white", children: _jsxs(View, { className: "flex-1 min-h-[100vh] justify-center items-center p-6 bg-slate-50/50", children: [_jsx(Button, { href: "/", variant: "ghost", size: "sm", className: "absolute top-10 left-6 flex-row gap-1", label: "Back", icon: _jsx(ChevronLeft, { size: 16, color: "#64748b" }) }), _jsxs(Card, { className: "w-full max-w-md shadow-2xl shadow-slate-200 border-none bg-white py-4", children: [_jsxs(CardHeader, { className: "items-center pb-2", children: [_jsx(View, { className: "w-14 h-14 bg-blue-600 rounded-2xl items-center justify-center mb-6 shadow-xl shadow-blue-200", children: _jsx(Shield, { color: "white", size: 28 }) }), _jsx(H1, { className: "text-3xl text-slate-900 border-none", children: "Sign In" }), _jsx(Lead, { className: "text-center text-slate-500 mt-2 px-4", children: "One-click access to your strategic playbook canvas with Supabase & Google" })] }), _jsxs(CardContent, { className: "gap-8 pt-8 px-8", children: [_jsx(Button, { route: "dashboard", variant: "outline", size: "lg", className: "w-full border-slate-200 py-4 h-16", icon: _jsx(Chrome, { size: 20, color: "#000" }), label: "Continue with Google", textClassName: "text-slate-900 text-lg" }), _jsxs(View, { className: "flex-row items-center gap-4", children: [_jsx(View, { className: "flex-1 h-[1px] bg-slate-100" }), _jsx(Text, { className: "text-slate-300 text-xs font-bold uppercase tracking-widest", children: "Secured by Supabase" }), _jsx(View, { className: "flex-1 h-[1px] bg-slate-100" })] }), _jsx(View, { className: "items-center", children: _jsxs(Small, { className: "text-center text-slate-400 leading-relaxed", children: ["By continuing, you agree to GrowthPad's", "\n", _jsx(Text, { className: "text-blue-600", children: "Terms of Service" }), " and ", _jsx(Text, { className: "text-blue-600", children: "Privacy Policy" }), "."] }) })] })] }), _jsxs(View, { className: "mt-10 flex-row gap-8 opacity-40", children: [_jsx(Shield, { size: 20, color: "#64748b" }), _jsx(View, { className: "w-5 h-5 bg-slate-400 rounded-sm" }), _jsx(View, { className: "w-5 h-5 bg-slate-400 rounded-full" })] })] }) }));
}
